import type { CnMediaSource } from './types';

/** 第一財經完整節目與可公開轉錄的 B站 A 股創作者；分析時會保留來源層級。 */
export const DEFAULT_CN_MEDIA_SOURCES: CnMediaSource[] = [
  {
    source_id: 'yicai-investment-view',
    display_name: '第一財經・投資有看頭',
    platform: 'yicai',
    url: 'https://www.yicai.com/video/youkantou/',
    expected_cadence: 'weekday',
    active: true,
    default_analysts: ['投資有看頭'],
    source_tier: 'official_media',
  },
  {
    source_id: 'yicai-today-market',
    display_name: '第一財經・今日股市',
    platform: 'yicai',
    url: 'https://www.yicai.com/video/jinrigushi/',
    expected_cadence: 'weekday',
    active: true,
    default_analysts: ['今日股市'],
    source_tier: 'official_media',
  },
  {
    source_id: 'yicai-company-industry',
    display_name: '第一財經・公司與行業',
    platform: 'yicai',
    url: 'https://www.yicai.com/video/gongsiyuhangye/',
    expected_cadence: 'weekday',
    active: true,
    default_analysts: ['公司與行業'],
    source_tier: 'official_media',
  },
  {
    source_id: 'yicai-stock-talk',
    display_name: '第一財經・談股論金',
    platform: 'yicai',
    url: 'https://www.yicai.com/video/tangulunjin/',
    expected_cadence: 'weekday',
    active: true,
    default_analysts: ['談股論金'],
    source_tier: 'official_media',
  },
  {
    source_id: 'yicai-stock-everyone',
    display_name: '第一財經・股市大家談',
    platform: 'yicai',
    url: 'https://www.yicai.com/video/gsdjt/',
    expected_cadence: 'weekday',
    active: true,
    default_analysts: ['股市大家談'],
    source_tier: 'official_media',
  },
  {
    source_id: 'bilibili-yami-dad-stocks',
    display_name: 'B站・娅米爸爸講股市',
    platform: 'bilibili',
    url: 'https://space.bilibili.com/397589042/video',
    expected_cadence: 'weekday',
    active: true,
    default_analysts: ['娅米爸爸'],
    source_tier: 'creator',
    include_title_keywords: ['股市', '股票', 'A股', '大盘', '板块', 'ETF', '复盘'],
    search_query: '娅米爸爸讲股市',
    search_pages: 3,
  },
  {
    source_id: 'bilibili-fintalk-industry',
    display_name: 'B站・FinTalk 財智新聲',
    platform: 'bilibili',
    url: 'https://space.bilibili.com/3546656144362381/video',
    expected_cadence: 'weekly',
    active: true,
    default_analysts: ['拆解橘'],
    source_tier: 'creator',
    search_query: '拆解橘',
    search_pages: 10,
  },
  {
    source_id: 'bilibili-beikan-aspects',
    display_name: 'B站・貝侃非典型政經',
    platform: 'bilibili',
    url: 'https://space.bilibili.com/1226974365/video',
    expected_cadence: 'weekday',
    active: true,
    default_analysts: ['貝侃'],
    source_tier: 'creator',
    include_title_keywords: ['A股', '大A', '股市', '股票', '盘后', '沪指', '创业板', '板块'],
    search_queries: ['贝侃 A股', '贝侃-非典型政经 大A'],
    search_pages: 5,
  },
  {
    source_id: 'bilibili-value-office',
    display_name: 'B站・價值事務所',
    platform: 'bilibili',
    url: 'https://space.bilibili.com/394889148/video',
    expected_cadence: 'irregular',
    active: true,
    default_analysts: ['價值事務所'],
    source_tier: 'creator',
    search_queries: ['价值事务所 {year}', '价值事务所 股票'],
    search_pages: 5,
  },
  {
    source_id: 'bilibili-dongge-market',
    display_name: 'B站・冬哥論市',
    platform: 'bilibili',
    url: 'https://space.bilibili.com/1692785842/video',
    expected_cadence: 'weekday',
    active: true,
    default_analysts: ['冬哥'],
    source_tier: 'creator',
    search_queries: ['冬哥论市 A股', '冬哥论市 复盘'],
    search_pages: 5,
  },
  {
    source_id: 'bilibili-laoke-review',
    display_name: 'B站・老柯復盤',
    platform: 'bilibili',
    url: 'https://space.bilibili.com/3546635351099881/video',
    expected_cadence: 'weekday',
    active: true,
    default_analysts: ['老柯'],
    source_tier: 'creator',
    search_queries: ['老柯复盘', 'A股复盘 老柯'],
    search_pages: 5,
  },
  {
    source_id: 'bilibili-laicongxin-review',
    display_name: 'B站・來去由心',
    platform: 'bilibili',
    url: 'https://space.bilibili.com/11430504/video',
    expected_cadence: 'weekday',
    active: true,
    default_analysts: ['來去由心'],
    source_tier: 'creator',
    include_title_keywords: ['A股', '股票', '科技', '医药', '资金', '题材', '板块', '低吸', '利好', '复盘'],
    search_queries: ['来去由心', '来去由心 A股', '来去由心 科技 医药'],
    search_pages: 8,
  },
  {
    source_id: 'bilibili-niusan-zhaoge',
    display_name: 'B站・牛散趙哥',
    platform: 'bilibili',
    url: 'https://space.bilibili.com/1593359860/video',
    expected_cadence: 'weekday',
    active: true,
    default_analysts: ['牛散趙哥'],
    source_tier: 'creator',
    include_title_keywords: ['A股', '股票', '股市', '板块', '大盘', '市场', '资金', '科技', '医药', '行情', '操作策略'],
    search_queries: ['牛散赵哥', '牛散赵哥 A股', '牛散赵哥 科技', '牛散赵哥 创新药'],
    search_pages: 8,
  },
  {
    source_id: 'bilibili-xueliang-short-review',
    display_name: 'B站・雪亮超短復盤',
    platform: 'bilibili',
    url: 'https://space.bilibili.com/345681438/video',
    expected_cadence: 'weekday',
    active: true,
    default_analysts: ['雪亮超短復盤'],
    source_tier: 'creator',
    include_title_keywords: ['超短复盘'],
    search_query: '雪亮超短复盘',
    search_pages: 5,
  },
  {
    source_id: 'bilibili-zhujijiaoyiyuan-review',
    display_name: 'B站・築基交易員',
    platform: 'bilibili',
    url: 'https://space.bilibili.com/497120492/video',
    expected_cadence: 'irregular',
    active: true,
    default_analysts: ['築基交易員'],
    source_tier: 'creator',
    include_title_keywords: ['复盘'],
    search_queries: ['筑基交易员', '筑基交易员 复盘', '筑基交易员 A股'],
    search_pages: 8,
  },
  {
    source_id: 'bilibili-guwangjinshi168-stock-review',
    display_name: 'B站・股往金事168',
    platform: 'bilibili',
    url: 'https://space.bilibili.com/1252590958/video',
    expected_cadence: 'weekday',
    active: true,
    default_analysts: ['股往金事168'],
    source_tier: 'creator',
    include_title_keywords: ['人气股票分析思路'],
    search_queries: ['股往金事168 {month_day} 人气股票分析思路', '股往金事168 人气股票分析思路'],
    search_pages: 10,
  },
];

export function defaultCnMediaSources(): CnMediaSource[] {
  return DEFAULT_CN_MEDIA_SOURCES.map(source => ({
    ...source,
    default_analysts: [...source.default_analysts],
  }));
}
