// ⚠️ 自動產生，請勿手改。來源：data/backtest/sell-heaviness.json（scope=uptrend）
// 重跑：npx tsx scripts/gen-sell-heaviness-table.ts
// 賣訊輕重：訊號觸發後相對「同日同儕宇宙」的前瞻 alpha（越負＝越重）；分級用 worst-of-{d5,d10,d20}。
// 視窗：2024-04-29 ~ 2026-04-24（2y）。判決為本視窗本市場特定。

export type SellTier = 'heavy' | 'medium' | 'light' | 'lagging' | 'noisy';

export interface SellHeavinessEntry {
  tier: SellTier;
  alphaD5: number; alphaD10: number; alphaD20: number; worst: number;
  firings: number;
  reliable: boolean;        // 統計顯著且樣本足
  significant: boolean;
  stable: boolean;
  declaredSeverity: 'high' | 'medium' | 'low' | null;
  verdict: 'agree' | 'overrated' | 'underrated' | 'n/a';
  family: 'book' | 'sanse' | 'combo';
  label: string;
  note: string;
}

export const SELL_HEAVINESS_WINDOW = {"start":"2024-04-29","end":"2026-04-24","label":"2y"} as const;

export const SELL_HEAVINESS: Record<'TW' | 'CN', Record<string, SellHeavinessEntry>> = {
  "TW": {
    "b_breakdn": {
      "tier": "noisy",
      "alphaD5": -0.04,
      "alphaD10": -0.06,
      "alphaD20": -0.08,
      "worst": -0.08,
      "firings": 7660,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": null,
      "verdict": "n/a",
      "family": "sanse",
      "label": "跌破智能交易線",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "b_dead": {
      "tier": "noisy",
      "alphaD5": -0.11,
      "alphaD10": -0.98,
      "alphaD20": -1.93,
      "worst": -1.93,
      "firings": 136,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": null,
      "verdict": "n/a",
      "family": "sanse",
      "label": "雙B死叉（黃跌破紅）",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "b_sresonance": {
      "tier": "noisy",
      "alphaD5": -0.15,
      "alphaD10": -1.22,
      "alphaD20": -1.04,
      "worst": -1.22,
      "firings": 76,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": null,
      "verdict": "n/a",
      "family": "sanse",
      "label": "雙重共振（死叉+跌破同日）",
      "note": "樣本太少，參考性低（別據此單獨動作）"
    },
    "BREAK_MA10": {
      "tier": "medium",
      "alphaD5": -0.19,
      "alphaD10": -0.32,
      "alphaD20": -0.41,
      "worst": -0.41,
      "firings": 8249,
      "reliable": true,
      "significant": true,
      "stable": false,
      "declaredSeverity": "high",
      "verdict": "overrated",
      "family": "book",
      "label": "跌破MA10",
      "note": "中等：會輸同儕但非急殺；手寫嚴重度偏高；半窗不夠穩定"
    },
    "BREAK_MA20": {
      "tier": "noisy",
      "alphaD5": -0.01,
      "alphaD10": -0.34,
      "alphaD20": -0.57,
      "worst": -0.57,
      "firings": 2849,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": "high",
      "verdict": "overrated",
      "family": "book",
      "label": "跌破月線",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "BREAK_MA5": {
      "tier": "medium",
      "alphaD5": -0.16,
      "alphaD10": -0.18,
      "alphaD20": -0.32,
      "worst": -0.32,
      "firings": 11248,
      "reliable": true,
      "significant": true,
      "stable": true,
      "declaredSeverity": "low",
      "verdict": "underrated",
      "family": "book",
      "label": "跌破週線MA5",
      "note": "中等：會輸同儕但非急殺；手寫嚴重度偏低（值得更當心）"
    },
    "c_dead": {
      "tier": "medium",
      "alphaD5": -0.26,
      "alphaD10": -0.3,
      "alphaD20": -0.35,
      "worst": -0.35,
      "firings": 14297,
      "reliable": true,
      "significant": true,
      "stable": true,
      "declaredSeverity": null,
      "verdict": "n/a",
      "family": "sanse",
      "label": "捕撈動能死叉",
      "note": "中等：會輸同儕但非急殺"
    },
    "combo:BREAK_MA10+KD_DEATH_CROSS": {
      "tier": "heavy",
      "alphaD5": -1.36,
      "alphaD10": -1.57,
      "alphaD20": -1.67,
      "worst": -1.67,
      "firings": 143,
      "reliable": true,
      "significant": true,
      "stable": false,
      "declaredSeverity": null,
      "verdict": "n/a",
      "family": "combo",
      "label": "跌破MA10＋KD高位死叉",
      "note": "實測偏重，訊號後明顯弱於同儕；半窗不夠穩定"
    },
    "combo:DEATH_CROSS+BREAK_MA20": {
      "tier": "noisy",
      "alphaD5": -0.22,
      "alphaD10": -0.62,
      "alphaD20": -1.22,
      "worst": -1.22,
      "firings": 409,
      "reliable": false,
      "significant": false,
      "stable": true,
      "declaredSeverity": null,
      "verdict": "n/a",
      "family": "combo",
      "label": "死叉＋跌破月線（趨勢真破）",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "combo:HIGH_SEVERITY>=2": {
      "tier": "noisy",
      "alphaD5": -0.14,
      "alphaD10": -0.29,
      "alphaD20": -0.42,
      "worst": -0.42,
      "firings": 10458,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": null,
      "verdict": "n/a",
      "family": "combo",
      "label": "同根 ≥2 個 high 訊號",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "DEATH_CROSS": {
      "tier": "noisy",
      "alphaD5": 0.18,
      "alphaD10": -0.33,
      "alphaD20": -0.95,
      "worst": -0.95,
      "firings": 670,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": "high",
      "verdict": "agree",
      "family": "book",
      "label": "死亡交叉",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "HIGH_LEVEL_BEARISH_ENGULF": {
      "tier": "noisy",
      "alphaD5": 0.35,
      "alphaD10": 0.45,
      "alphaD20": 0.27,
      "worst": 0.27,
      "firings": 1157,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": "high",
      "verdict": "overrated",
      "family": "book",
      "label": "高檔陰包陽",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "HIGH_LEVEL_DOJI": {
      "tier": "noisy",
      "alphaD5": -0.23,
      "alphaD10": -0.01,
      "alphaD20": -0.12,
      "worst": -0.23,
      "firings": 2004,
      "reliable": false,
      "significant": false,
      "stable": true,
      "declaredSeverity": "high",
      "verdict": "overrated",
      "family": "book",
      "label": "高檔十字後破低",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "HIGH_LEVEL_HANGING_MAN": {
      "tier": "noisy",
      "alphaD5": 0.25,
      "alphaD10": 0.17,
      "alphaD20": -0.82,
      "worst": -0.82,
      "firings": 324,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": "high",
      "verdict": "agree",
      "family": "book",
      "label": "高檔吊人破低",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "HIGH_LEVEL_OPEN_FLAT_BLACK": {
      "tier": "noisy",
      "alphaD5": -0.18,
      "alphaD10": -0.42,
      "alphaD20": -0.31,
      "worst": -0.42,
      "firings": 1565,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": "high",
      "verdict": "overrated",
      "family": "book",
      "label": "高檔開平低長黑",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "HIGH_VOL_2DAY_3BLACK": {
      "tier": "noisy",
      "alphaD5": -0.02,
      "alphaD10": -0.85,
      "alphaD20": -0.72,
      "worst": -0.85,
      "firings": 376,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": "high",
      "verdict": "agree",
      "family": "book",
      "label": "爆量後連3黑",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "HIGH_VOL_UPPER_SHADOW": {
      "tier": "noisy",
      "alphaD5": -0.22,
      "alphaD10": -0.12,
      "alphaD20": 0.33,
      "worst": -0.22,
      "firings": 3816,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": "high",
      "verdict": "overrated",
      "family": "book",
      "label": "高檔爆量上影線",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "KD_DEATH_CROSS": {
      "tier": "noisy",
      "alphaD5": -0.06,
      "alphaD10": 0.14,
      "alphaD20": 0.15,
      "worst": -0.06,
      "firings": 2892,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": "medium",
      "verdict": "overrated",
      "family": "book",
      "label": "KD高位死叉",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "LOWER_LOW": {
      "tier": "noisy",
      "alphaD5": 0,
      "alphaD10": -0.02,
      "alphaD20": -0.07,
      "worst": -0.07,
      "firings": 5328,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": "high",
      "verdict": "overrated",
      "family": "book",
      "label": "頭頭低出場",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "m_weak": {
      "tier": "noisy",
      "alphaD5": -0.17,
      "alphaD10": -0.21,
      "alphaD20": -0.41,
      "worst": -0.41,
      "firings": 1527,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": null,
      "verdict": "n/a",
      "family": "sanse",
      "label": "主力轉弱（中線<0，研究事件）",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "PROFIT_CLIMAX_EXIT": {
      "tier": "noisy",
      "alphaD5": -0.04,
      "alphaD10": -0.14,
      "alphaD20": -0.19,
      "worst": -0.19,
      "firings": 1173,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": "high",
      "verdict": "overrated",
      "family": "book",
      "label": "急漲後長黑出場",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "RED_K_LOW_BREAK": {
      "tier": "noisy",
      "alphaD5": 0,
      "alphaD10": -0.12,
      "alphaD20": -0.2,
      "worst": -0.2,
      "firings": 5023,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": "high",
      "verdict": "overrated",
      "family": "book",
      "label": "跌破紅K低點",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "SEASON_LINE_DOWN_BREAK": {
      "tier": "noisy",
      "alphaD5": -0.33,
      "alphaD10": -0.65,
      "alphaD20": -1.19,
      "worst": -1.19,
      "firings": 1246,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": "medium",
      "verdict": "underrated",
      "family": "book",
      "label": "季線下彎破5均",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "STRONG_COVER": {
      "tier": "medium",
      "alphaD5": -0.24,
      "alphaD10": -0.35,
      "alphaD20": -0.54,
      "worst": -0.54,
      "firings": 11275,
      "reliable": true,
      "significant": true,
      "stable": true,
      "declaredSeverity": "medium",
      "verdict": "agree",
      "family": "book",
      "label": "強覆蓋減碼",
      "note": "中等：會輸同儕但非急殺"
    },
    "SUPPORT_BREAK_STOPLOSS": {
      "tier": "heavy",
      "alphaD5": -0.31,
      "alphaD10": -0.87,
      "alphaD20": -1.39,
      "worst": -1.39,
      "firings": 3199,
      "reliable": true,
      "significant": true,
      "stable": true,
      "declaredSeverity": "high",
      "verdict": "agree",
      "family": "book",
      "label": "關鍵支撐跌破",
      "note": "實測偏重，訊號後明顯弱於同儕"
    },
    "TREND_BEARISH": {
      "tier": "noisy",
      "alphaD5": -0.22,
      "alphaD10": -0.52,
      "alphaD20": -0.51,
      "worst": -0.52,
      "firings": 1779,
      "reliable": false,
      "significant": false,
      "stable": true,
      "declaredSeverity": "high",
      "verdict": "overrated",
      "family": "book",
      "label": "空頭趨勢確認",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "TRENDLINE_BREAK_BLACK": {
      "tier": "noisy",
      "alphaD5": -0.07,
      "alphaD10": -0.15,
      "alphaD20": -0.32,
      "worst": -0.32,
      "firings": 6427,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": "high",
      "verdict": "overrated",
      "family": "book",
      "label": "跌破切線長黑",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "WEEKLY_RESIST_BREAK_MA5": {
      "tier": "heavy",
      "alphaD5": -0.72,
      "alphaD10": -1.48,
      "alphaD20": -1.78,
      "worst": -1.78,
      "firings": 797,
      "reliable": true,
      "significant": true,
      "stable": false,
      "declaredSeverity": "high",
      "verdict": "agree",
      "family": "book",
      "label": "遇壓破MA5",
      "note": "實測偏重，訊號後明顯弱於同儕；半窗不夠穩定"
    }
  },
  "CN": {
    "b_breakdn": {
      "tier": "heavy",
      "alphaD5": -0.33,
      "alphaD10": -0.59,
      "alphaD20": -0.7,
      "worst": -0.7,
      "firings": 13575,
      "reliable": true,
      "significant": true,
      "stable": false,
      "declaredSeverity": null,
      "verdict": "n/a",
      "family": "sanse",
      "label": "跌破智能交易線",
      "note": "實測偏重，訊號後明顯弱於同儕；半窗不夠穩定"
    },
    "b_dead": {
      "tier": "noisy",
      "alphaD5": -0.53,
      "alphaD10": -0.56,
      "alphaD20": 0.48,
      "worst": -0.56,
      "firings": 151,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": null,
      "verdict": "n/a",
      "family": "sanse",
      "label": "雙B死叉（黃跌破紅）",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "b_sresonance": {
      "tier": "noisy",
      "alphaD5": -0.01,
      "alphaD10": -0.33,
      "alphaD20": 0.46,
      "worst": -0.33,
      "firings": 73,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": null,
      "verdict": "n/a",
      "family": "sanse",
      "label": "雙重共振（死叉+跌破同日）",
      "note": "樣本太少，參考性低（別據此單獨動作）"
    },
    "BREAK_MA10": {
      "tier": "lagging",
      "alphaD5": 0.29,
      "alphaD10": 0.3,
      "alphaD20": 0.4,
      "worst": 0.29,
      "firings": 13476,
      "reliable": true,
      "significant": true,
      "stable": true,
      "declaredSeverity": "high",
      "verdict": "overrated",
      "family": "book",
      "label": "跌破MA10",
      "note": "落後/反指：破線時行情多已走完，平均反而略強同儕；手寫嚴重度偏高"
    },
    "BREAK_MA20": {
      "tier": "lagging",
      "alphaD5": 0.38,
      "alphaD10": 0.45,
      "alphaD20": 0.89,
      "worst": 0.38,
      "firings": 4746,
      "reliable": true,
      "significant": true,
      "stable": true,
      "declaredSeverity": "high",
      "verdict": "overrated",
      "family": "book",
      "label": "跌破月線",
      "note": "落後/反指：破線時行情多已走完，平均反而略強同儕；手寫嚴重度偏高"
    },
    "BREAK_MA5": {
      "tier": "lagging",
      "alphaD5": 0.16,
      "alphaD10": 0.13,
      "alphaD20": -0.02,
      "worst": -0.02,
      "firings": 19223,
      "reliable": true,
      "significant": true,
      "stable": true,
      "declaredSeverity": "low",
      "verdict": "agree",
      "family": "book",
      "label": "跌破週線MA5",
      "note": "落後/反指：破線時行情多已走完，平均反而略強同儕"
    },
    "c_dead": {
      "tier": "light",
      "alphaD5": -0.18,
      "alphaD10": -0.16,
      "alphaD20": -0.13,
      "worst": -0.18,
      "firings": 24936,
      "reliable": true,
      "significant": true,
      "stable": true,
      "declaredSeverity": null,
      "verdict": "n/a",
      "family": "sanse",
      "label": "捕撈動能死叉",
      "note": "偏輕：慢慢輸同儕、非急殺"
    },
    "combo:BREAK_MA10+KD_DEATH_CROSS": {
      "tier": "noisy",
      "alphaD5": 0.58,
      "alphaD10": 0.23,
      "alphaD20": -1.1,
      "worst": -1.1,
      "firings": 158,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": null,
      "verdict": "n/a",
      "family": "combo",
      "label": "跌破MA10＋KD高位死叉",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "combo:DEATH_CROSS+BREAK_MA20": {
      "tier": "noisy",
      "alphaD5": 0.47,
      "alphaD10": 0.34,
      "alphaD20": 1.34,
      "worst": 0.34,
      "firings": 594,
      "reliable": false,
      "significant": false,
      "stable": true,
      "declaredSeverity": null,
      "verdict": "n/a",
      "family": "combo",
      "label": "死叉＋跌破月線（趨勢真破）",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "combo:HIGH_SEVERITY>=2": {
      "tier": "lagging",
      "alphaD5": 0.22,
      "alphaD10": 0.17,
      "alphaD20": 0.14,
      "worst": 0.14,
      "firings": 17448,
      "reliable": true,
      "significant": true,
      "stable": false,
      "declaredSeverity": null,
      "verdict": "n/a",
      "family": "combo",
      "label": "同根 ≥2 個 high 訊號",
      "note": "落後/反指：破線時行情多已走完，平均反而略強同儕；半窗不夠穩定"
    },
    "DEATH_CROSS": {
      "tier": "lagging",
      "alphaD5": 0.59,
      "alphaD10": 0.53,
      "alphaD20": 1.1,
      "worst": 0.53,
      "firings": 981,
      "reliable": true,
      "significant": true,
      "stable": true,
      "declaredSeverity": "high",
      "verdict": "overrated",
      "family": "book",
      "label": "死亡交叉",
      "note": "落後/反指：破線時行情多已走完，平均反而略強同儕；手寫嚴重度偏高"
    },
    "HIGH_LEVEL_BEARISH_ENGULF": {
      "tier": "noisy",
      "alphaD5": -0.11,
      "alphaD10": -0.2,
      "alphaD20": -0.4,
      "worst": -0.4,
      "firings": 1144,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": "high",
      "verdict": "overrated",
      "family": "book",
      "label": "高檔陰包陽",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "HIGH_LEVEL_DOJI": {
      "tier": "noisy",
      "alphaD5": -0.16,
      "alphaD10": -0.12,
      "alphaD20": 0.16,
      "worst": -0.16,
      "firings": 3874,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": "high",
      "verdict": "overrated",
      "family": "book",
      "label": "高檔十字後破低",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "HIGH_LEVEL_HANGING_MAN": {
      "tier": "heavy",
      "alphaD5": -1.23,
      "alphaD10": -0.42,
      "alphaD20": -0.13,
      "worst": -1.23,
      "firings": 383,
      "reliable": true,
      "significant": true,
      "stable": true,
      "declaredSeverity": "high",
      "verdict": "agree",
      "family": "book",
      "label": "高檔吊人破低",
      "note": "實測偏重，訊號後明顯弱於同儕"
    },
    "HIGH_LEVEL_OPEN_FLAT_BLACK": {
      "tier": "lagging",
      "alphaD5": 0.56,
      "alphaD10": 0.73,
      "alphaD20": 0.78,
      "worst": 0.56,
      "firings": 3066,
      "reliable": true,
      "significant": true,
      "stable": false,
      "declaredSeverity": "high",
      "verdict": "overrated",
      "family": "book",
      "label": "高檔開平低長黑",
      "note": "落後/反指：破線時行情多已走完，平均反而略強同儕；手寫嚴重度偏高；半窗不夠穩定"
    },
    "HIGH_VOL_2DAY_3BLACK": {
      "tier": "noisy",
      "alphaD5": 0.39,
      "alphaD10": 0.27,
      "alphaD20": 0.01,
      "worst": 0.01,
      "firings": 36,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": "high",
      "verdict": "n/a",
      "family": "book",
      "label": "爆量後連3黑",
      "note": "樣本太少，參考性低（別據此單獨動作）"
    },
    "HIGH_VOL_UPPER_SHADOW": {
      "tier": "heavy",
      "alphaD5": -0.67,
      "alphaD10": -0.54,
      "alphaD20": -0.92,
      "worst": -0.92,
      "firings": 5058,
      "reliable": true,
      "significant": true,
      "stable": true,
      "declaredSeverity": "high",
      "verdict": "agree",
      "family": "book",
      "label": "高檔爆量上影線",
      "note": "實測偏重，訊號後明顯弱於同儕"
    },
    "KD_DEATH_CROSS": {
      "tier": "heavy",
      "alphaD5": -0.9,
      "alphaD10": -1.14,
      "alphaD20": -1.11,
      "worst": -1.14,
      "firings": 5153,
      "reliable": true,
      "significant": true,
      "stable": true,
      "declaredSeverity": "medium",
      "verdict": "underrated",
      "family": "book",
      "label": "KD高位死叉",
      "note": "實測偏重，訊號後明顯弱於同儕；手寫嚴重度偏低（值得更當心）"
    },
    "LOWER_LOW": {
      "tier": "lagging",
      "alphaD5": 0.26,
      "alphaD10": 0.24,
      "alphaD20": 0.29,
      "worst": 0.24,
      "firings": 9219,
      "reliable": true,
      "significant": true,
      "stable": true,
      "declaredSeverity": "high",
      "verdict": "overrated",
      "family": "book",
      "label": "頭頭低出場",
      "note": "落後/反指：破線時行情多已走完，平均反而略強同儕；手寫嚴重度偏高"
    },
    "m_weak": {
      "tier": "medium",
      "alphaD5": 0.36,
      "alphaD10": 0.17,
      "alphaD20": -0.26,
      "worst": -0.26,
      "firings": 3317,
      "reliable": true,
      "significant": true,
      "stable": false,
      "declaredSeverity": null,
      "verdict": "n/a",
      "family": "sanse",
      "label": "主力轉弱（中線<0，研究事件）",
      "note": "中等：會輸同儕但非急殺；半窗不夠穩定"
    },
    "PROFIT_CLIMAX_EXIT": {
      "tier": "heavy",
      "alphaD5": -0.39,
      "alphaD10": -0.76,
      "alphaD20": -1.28,
      "worst": -1.28,
      "firings": 2518,
      "reliable": true,
      "significant": true,
      "stable": false,
      "declaredSeverity": "high",
      "verdict": "agree",
      "family": "book",
      "label": "急漲後長黑出場",
      "note": "實測偏重，訊號後明顯弱於同儕；半窗不夠穩定"
    },
    "RED_K_LOW_BREAK": {
      "tier": "noisy",
      "alphaD5": 0.05,
      "alphaD10": -0.08,
      "alphaD20": -0.1,
      "worst": -0.1,
      "firings": 10864,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": "high",
      "verdict": "overrated",
      "family": "book",
      "label": "跌破紅K低點",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "SEASON_LINE_DOWN_BREAK": {
      "tier": "noisy",
      "alphaD5": 0.1,
      "alphaD10": -0.05,
      "alphaD20": -0.66,
      "worst": -0.66,
      "firings": 1763,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": "medium",
      "verdict": "underrated",
      "family": "book",
      "label": "季線下彎破5均",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "STRONG_COVER": {
      "tier": "noisy",
      "alphaD5": 0.01,
      "alphaD10": -0.06,
      "alphaD20": -0.1,
      "worst": -0.1,
      "firings": 23075,
      "reliable": false,
      "significant": false,
      "stable": false,
      "declaredSeverity": "medium",
      "verdict": "overrated",
      "family": "book",
      "label": "強覆蓋減碼",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    },
    "SUPPORT_BREAK_STOPLOSS": {
      "tier": "lagging",
      "alphaD5": 0.29,
      "alphaD10": 0.2,
      "alphaD20": 0.55,
      "worst": 0.2,
      "firings": 4971,
      "reliable": true,
      "significant": true,
      "stable": false,
      "declaredSeverity": "high",
      "verdict": "overrated",
      "family": "book",
      "label": "關鍵支撐跌破",
      "note": "落後/反指：破線時行情多已走完，平均反而略強同儕；手寫嚴重度偏高；半窗不夠穩定"
    },
    "TREND_BEARISH": {
      "tier": "lagging",
      "alphaD5": 0.38,
      "alphaD10": 0.2,
      "alphaD20": 0.21,
      "worst": 0.2,
      "firings": 2658,
      "reliable": true,
      "significant": true,
      "stable": true,
      "declaredSeverity": "high",
      "verdict": "overrated",
      "family": "book",
      "label": "空頭趨勢確認",
      "note": "落後/反指：破線時行情多已走完，平均反而略強同儕；手寫嚴重度偏高"
    },
    "TRENDLINE_BREAK_BLACK": {
      "tier": "lagging",
      "alphaD5": 0.25,
      "alphaD10": 0.26,
      "alphaD20": 0.22,
      "worst": 0.22,
      "firings": 10515,
      "reliable": true,
      "significant": true,
      "stable": false,
      "declaredSeverity": "high",
      "verdict": "overrated",
      "family": "book",
      "label": "跌破切線長黑",
      "note": "落後/反指：破線時行情多已走完，平均反而略強同儕；手寫嚴重度偏高；半窗不夠穩定"
    },
    "WEEKLY_RESIST_BREAK_MA5": {
      "tier": "noisy",
      "alphaD5": 0.13,
      "alphaD10": 0.29,
      "alphaD20": 0.47,
      "worst": 0.13,
      "firings": 1275,
      "reliable": false,
      "significant": false,
      "stable": true,
      "declaredSeverity": "high",
      "verdict": "overrated",
      "family": "book",
      "label": "遇壓破MA5",
      "note": "本市場無顯著 edge：訊號後與同儕無明顯差異，別單獨據此動作"
    }
  }
};

/** 查某市場某賣訊（id = 三色 b_dead… 或書本 DEATH_CROSS…）的輕重；查不到回 null。 */
export function lookupSellHeaviness(
  market: 'TW' | 'CN' | 'other' | undefined,
  signalId: string,
): SellHeavinessEntry | null {
  if (market !== 'TW' && market !== 'CN') return null;
  return SELL_HEAVINESS[market][signalId] ?? null;
}
