/**
 * 生成完整的滬深主板 A 股清單
 *
 * 用 Yahoo Finance v8 API 批量驗證代碼是否存在
 * 滬A主板: 600000-605999 (.SS)
 * 深A主板: 000001-003999 (.SZ)
 *
 * Usage: npx tsx scripts/generate-cn-stocklist.ts
 */
import fs from 'fs';
import path from 'path';

const YF_HEADERS = { 'User-Agent': 'Mozilla/5.0 (Macintosh)' };
const CONCURRENCY = 30;

interface StockInfo {
  symbol: string;
  name: string;
}

/** 用 Yahoo Finance v8 chart API 驗證一個 symbol 是否存在 */
async function checkSymbol(symbol: string): Promise<StockInfo | null> {
  try {
    const url = `https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?interval=1d&range=5d&includePrePost=false`;
    const res = await fetch(url, {
      headers: YF_HEADERS,
      signal: AbortSignal.timeout(10000),
    });
    if (!res.ok) return null;
    const json = await res.json();
    const result = json?.chart?.result?.[0];
    if (!result || !result.timestamp || result.timestamp.length === 0) return null;
    const name = result.meta?.longName || result.meta?.shortName || symbol.split('.')[0];
    return { symbol, name };
  } catch {
    return null;
  }
}

/** 批量驗證 symbols，CONCURRENCY 個併發 */
async function batchCheck(symbols: string[]): Promise<StockInfo[]> {
  const results: StockInfo[] = [];
  for (let i = 0; i < symbols.length; i += CONCURRENCY) {
    const batch = symbols.slice(i, i + CONCURRENCY);
    const settled = await Promise.allSettled(batch.map(s => checkSymbol(s)));
    for (const r of settled) {
      if (r.status === 'fulfilled' && r.value) {
        results.push(r.value);
      }
    }
    if ((i + CONCURRENCY) % 300 === 0 || i + CONCURRENCY >= symbols.length) {
      console.log(`   ${Math.min(i + CONCURRENCY, symbols.length)}/${symbols.length}  有效: ${results.length}`);
    }
  }
  return results;
}

async function main() {
  console.log('═══ 生成滬深主板 A 股清單 ═══\n');

  // 滬A主板代碼範圍：600000-605999
  const shSymbols: string[] = [];
  for (let i = 600000; i <= 605999; i++) {
    shSymbols.push(`${i.toString().padStart(6, '0')}.SS`);
  }

  // 深A主板代碼範圍：000001-003999
  const szSymbols: string[] = [];
  for (let i = 1; i <= 3999; i++) {
    szSymbols.push(`${i.toString().padStart(6, '0')}.SZ`);
  }

  console.log(`滬A候選: ${shSymbols.length}, 深A候選: ${szSymbols.length}\n`);

  console.log('🔍 驗證滬A主板...');
  const shStocks = await batchCheck(shSymbols);
  console.log(`   ✅ 滬A主板: ${shStocks.length} 支\n`);

  console.log('🔍 驗證深A主板...');
  const szStocks = await batchCheck(szSymbols);
  console.log(`   ✅ 深A主板: ${szStocks.length} 支\n`);

  const allStocks = [...shStocks, ...szStocks].sort((a, b) => a.symbol.localeCompare(b.symbol));
  console.log(`📊 合計: ${allStocks.length} 支 A 股（滬深主板）\n`);

  // 寫入 TypeScript 靜態清單
  const lines = allStocks.map(s =>
    `  { symbol: '${s.symbol}', name: '${s.name.replace(/'/g, "\\'")}' },`
  );

  const output = `// Auto-generated by scripts/generate-cn-stocklist.ts
// 滬A主板 + 深A主板（不含創業板300xxx、科創板688xxx）
// Generated: ${new Date().toISOString().split('T')[0]}
// Total: ${allStocks.length}

import type { StockEntry } from '../scanner/MarketScanner';

export const CN_STOCKS: StockEntry[] = [
${lines.join('\n')}
];
`;

  const outPath = path.join(process.cwd(), 'lib', 'scanner', 'cnStocks.ts');
  fs.writeFileSync(outPath, output, 'utf-8');
  console.log(`💾 已寫入 ${outPath}`);

  // 也存一份快取給東方財富 API 用（避免 API 失敗時 fallback 到舊清單）
  const cachePath = path.join(process.cwd(), 'data', 'cn_stocklist.json');
  if (!fs.existsSync(path.dirname(cachePath))) fs.mkdirSync(path.dirname(cachePath), { recursive: true });
  fs.writeFileSync(cachePath, JSON.stringify({
    updatedAt: new Date().toISOString(),
    stocks: allStocks.map(s => ({ symbol: s.symbol, name: s.name })),
  }));
  console.log(`💾 已寫入快取 ${cachePath}\n`);
}

main().catch(console.error);
