/**
 * 生成完整的滬深主板 A 股清單（中文名）
 *
 * 使用東方財富 push2 API 取得全部 A 股
 * f12=代碼, f14=中文名稱, f100=行業
 * fs: m:0+t:6(滬A主板), m:1+t:2(深A主板)
 *
 * Usage: npx tsx scripts/generate-cn-stocklist.ts
 */
import fs from 'fs';
import path from 'path';

interface StockInfo {
  symbol: string;
  name: string;
}

/** 從東方財富 API 抓取全部滬深主板 A 股 */
async function fetchFromEastMoney(): Promise<StockInfo[]> {
  const all: StockInfo[] = [];
  const pageSize = 100; // push2delay API 每頁最多 100 筆
  const maxPages = 50;  // 3500 / 100 = 35 頁，留餘量

  for (let page = 1; page <= maxPages; page++) {
    // 用 push2delay 避免 push2 的 302 redirect 問題
    const url = 'https://push2delay.eastmoney.com/api/qt/clist/get?' +
      `pn=${page}&pz=${pageSize}&po=1&np=1&fltt=2&invt=2&fid=f6` +
      '&fs=m:0+t:6,m:1+t:2' +
      '&fields=f12,f14,f3,f100';

    const res = await fetch(url, {
      headers: { 'User-Agent': 'Mozilla/5.0 (Macintosh)' },
      signal: AbortSignal.timeout(30000),
      redirect: 'follow',
    });

    if (!res.ok) throw new Error(`EastMoney API error: ${res.status}`);
    const json = await res.json();
    const items = json?.data?.diff;
    if (!items || items.length === 0) break;

    for (const item of items) {
      const code: string = item.f12;
      const name: string = item.f14;
      if (!code || !name) continue;
      // 過濾 ST、退市股
      if (name.includes('ST') || name.includes('退')) continue;

      // 判斷滬A (.SS) 或 深A (.SZ)
      const suffix = code.startsWith('6') ? '.SS' : '.SZ';
      all.push({ symbol: `${code}${suffix}`, name });
    }

    if (items.length < pageSize) break;
    if (page % 10 === 0) {
      console.log(`   第 ${page} 頁, 已取得 ${all.length} 筆`);
    }
    // 避免 API 限流
    await new Promise(r => setTimeout(r, 100));
  }

  return all;
}

async function main() {
  console.log('═══ 生成滬深主板 A 股清單（東方財富 API・中文名） ═══\n');

  console.log('🔍 從東方財富 API 取得股票清單...');
  const allStocks = (await fetchFromEastMoney())
    .sort((a, b) => a.symbol.localeCompare(b.symbol));

  const shCount = allStocks.filter(s => s.symbol.endsWith('.SS')).length;
  const szCount = allStocks.filter(s => s.symbol.endsWith('.SZ')).length;
  console.log(`   ✅ 滬A主板: ${shCount} 支`);
  console.log(`   ✅ 深A主板: ${szCount} 支`);
  console.log(`📊 合計: ${allStocks.length} 支 A 股（滬深主板）\n`);

  // 寫入 TypeScript 靜態清單
  const lines = allStocks.map(s =>
    `  { symbol: '${s.symbol}', name: '${s.name.replace(/'/g, "\\'")}' },`
  );

  const output = `// Auto-generated by scripts/generate-cn-stocklist.ts
// 滬A主板 + 深A主板（不含創業板300xxx、科創板688xxx）
// Source: 東方財富 push2 API（中文名）
// Generated: ${new Date().toISOString().split('T')[0]}
// Total: ${allStocks.length}

import type { StockEntry } from '../scanner/MarketScanner';

export const CN_STOCKS: StockEntry[] = [
${lines.join('\n')}
];
`;

  const outPath = path.join(process.cwd(), 'lib', 'scanner', 'cnStocks.ts');
  fs.writeFileSync(outPath, output, 'utf-8');
  console.log(`💾 已寫入 ${outPath}`);

  // 也存一份快取
  const cachePath = path.join(process.cwd(), 'data', 'cn_stocklist.json');
  if (!fs.existsSync(path.dirname(cachePath))) fs.mkdirSync(path.dirname(cachePath), { recursive: true });
  fs.writeFileSync(cachePath, JSON.stringify({
    updatedAt: new Date().toISOString(),
    stocks: allStocks.map(s => ({ symbol: s.symbol, name: s.name })),
  }));
  console.log(`💾 已寫入快取 ${cachePath}\n`);
}

main().catch(console.error);
